### ISSUE TITLE
Actualizacion del Cierre de caja

### ISSUE THREAD

**Issue by eychamba** [MASTERPC-CIA/bill_cierrecajanew#1]
Los datos para obtener la informacion sobre el cierre de caja han cambiado en la esctructura de la base de datos, por tanto es necesario obtener la informaci[on desde la tabla bill_asiento_contable, para que el cierre sea correcto.

**Comment by eychamba** [comment]
Esta ya tomando la informacion del pago desde asiento_contable_det?

**Comment by jaimejhonle** [comment]
no aun no
