### ISSUE TITLE
GENERAR CIERRE DE CAJA CON EFECTO DE COMPROBANTES DE INGRESO EGRESO DE CAJA

### ISSUE THREAD

**Issue by edymac** [MASTERPC-CIA/bill_cierrecajanew#2]
EN EL SISTEMA HAY CUENTAS CIONTABLES COMO CAJA GENERA Y CAJA CHICA , DE LAS CUALES HAY FLUJO DE EFECTIVO , SE DEBE REGISTRAR EN EKL CIERRE DE CAJA ESTE MOVIMIENTO :
----------------------------------------------------------------------------------------------------------
EJEMPLO : UN empleado pide 50 usd de anticipo y la cajera le da los 50 dolares se hace un comprobante que tiene anticipo suledo vs caja chica , en el cierre de caja estos 50 usd le falatrian a la cajera , por ello el cierre de caja debe expresar que ese dinero falta por un comprobante que se realizo.

**Comment by jaimejhonle** [comment]
El requirimiento esta listo
