### ISSUE TITLE
AGREGAR MOVIMIENTO NUEVO T. TRANSACCION

### ISSUE THREAD

**Issue by eychamba** [MASTERPC-CIA/bill_cierrecajanew#4]
Se ha creado un nuevo tipo de transaccion que afecta al cierre de caja, este es "DEVOLUCIONES RETENCION VENTA" cod 30.
Revisar para que los movimientos generados por esta transaccion se reflejen en el cierre de caja

**Comment by jaimejhonle** [comment]
El requerimiento esta cumplido
